site_name: afterB-wiki
site_description: ที่เก็บการ์ดแปลของ afterB
site_url: https://afterB-7.github.io/afterB-wiki/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
#  - Getting Started:
#      - How to Play: getting-started/how-to-play.md
  - Union Arena:
      - Overview: cards/index.md
      - IMC: 
          - All: cards/imc/imc.md
          - UA55ST: cards/imc/UA55ST.md
          - UA55BT: cards/imc/UA55BT.md
      - HTR: 
          - All: cards/htr/htr.md
          - UA03ST: cards/htr/UA03ST.md
          - UA03BT: cards/htr/UA03BT.md
          - EX01BT: cards/htr/EX01BT.md
          - UAPR: cards/htr/UAPR.md      
      - JJK: 
          - All: cards/jjk/jjk.md
          - UA02ST: cards/jjk/UA02ST.md
          - UA02BT: cards/jjk/UA02BT.md
          - UA02NC: cards/jjk/UA02NC.md
          - EX04BT: cards/jjk/EX04BT.md
      - CGH: 
          - All: cards/cgh/cgh.md
          - UA01ST: cards/cgh/UA01ST.md
          - UA01BT: cards/cgh/UA01BT.md
          - EX02BT: cards/cgh/EX02BT.md
          - UAPR: cards/cgh/UAPR.md


#  - About: about.md

markdown_extensions:
  - admonition
  - tables
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js
  - javascripts/card-viewer.js

plugins:
  - search:
      enabled: false