site_name: afterB-wiki
site_description: ที่เก็บการ์ดแปลของ afterB
site_url: https://afterB-7.github.io/afterB-wiki/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
#  - Getting Started:
#      - How to Play: getting-started/how-to-play.md
#      - Glossary: getting-started/glossary.md
  - UA Cards DB:
      - Overview: cards/index.md
      - CGH: 
          - Overview: cards/cgh/cgh.md
          - UA01ST: cards/cgh/UA01ST.md
#  - About: about.md

markdown_extensions:
  - admonition
  - tables
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
